"""empty message

Revision ID: 00c656809f58
Revises: ca662915758f
Create Date: 2022-04-08 14:25:08.558787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00c656809f58'
down_revision = 'ca662915758f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'caseName',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='用例名称')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'caseName',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='用例名称')
    # ### end Alembic commands ###
