"""empty message

Revision ID: 06cb13258769
Revises: ab68bdf7fdb1
Create Date: 2022-03-31 09:48:00.690096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06cb13258769'
down_revision = 'ab68bdf7fdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exe_case_record_detail',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recordNo', sa.String(length=30), nullable=False),
    sa.Column('caseId', sa.Integer(), nullable=True),
    sa.Column('consume', sa.String(length=10), nullable=False, comment='请求耗时'),
    sa.Column('data', sa.JSON(), nullable=False, comment='入参'),
    sa.Column('res', sa.JSON(), nullable=False, comment='返回值'),
    sa.Column('success', sa.Integer(), nullable=False, comment='用例执行是否成功 1 成功  2 失败'),
    sa.Column('env_id', sa.String(length=10), nullable=False, comment='环境id'),
    sa.ForeignKeyConstraint(['caseId'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wait_exe_case',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recordNo', sa.String(length=30), nullable=False),
    sa.Column('caseId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseId'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exe_case_record', sa.Column('recordNo', sa.String(length=30), nullable=False))
    op.drop_constraint('exe_case_record_ibfk_1', 'exe_case_record', type_='foreignkey')
    op.drop_column('exe_case_record', 'env_name')
    op.drop_column('exe_case_record', 'caseId')
    op.drop_column('exe_case_record', 'consume')
    op.drop_column('exe_case_record', 'success')
    op.drop_column('exe_case_record', 'res')
    op.drop_column('exe_case_record', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exe_case_record', sa.Column('data', mysql.JSON(), nullable=False))
    op.add_column('exe_case_record', sa.Column('res', mysql.JSON(), nullable=False))
    op.add_column('exe_case_record', sa.Column('success', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用例执行是否成功 1 成功  2 失败'))
    op.add_column('exe_case_record', sa.Column('consume', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('exe_case_record', sa.Column('caseId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exe_case_record', sa.Column('env_name', mysql.VARCHAR(length=10), nullable=False))
    op.create_foreign_key('exe_case_record_ibfk_1', 'exe_case_record', 'test_case', ['caseId'], ['id'])
    op.drop_column('exe_case_record', 'recordNo')
    op.drop_table('wait_exe_case')
    op.drop_table('exe_case_record_detail')
    # ### end Alembic commands ###
