"""empty message

Revision ID: 06f3237593cd
Revises: 
Create Date: 2022-03-23 20:53:17.647831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f3237593cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_config',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=150), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_module',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=150), nullable=False),
    sa.Column('header', sa.JSON(), nullable=False),
    sa.Column('param', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('dataType', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exe_case_record',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caseId', sa.Integer(), nullable=True),
    sa.Column('consume', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('res', sa.JSON(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('env_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['caseId'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ope_systems',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['main_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('func_module',
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ope_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('func_module')
    op.drop_table('ope_systems')
    op.drop_table('exe_case_record')
    op.drop_table('test_case')
    op.drop_table('main_module')
    op.drop_table('env_config')
    # ### end Alembic commands ###
