"""empty message

Revision ID: 18c83d14c83e
Revises: 541363c9cc7f
Create Date: 2022-03-31 10:16:37.723462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18c83d14c83e'
down_revision = '541363c9cc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'consume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='请求耗时')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'consume',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='请求耗时')
    # ### end Alembic commands ###
