"""empty message

Revision ID: 3cf6e5a62e2a
Revises: a15d880176aa
Create Date: 2022-03-28 11:54:26.425045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cf6e5a62e2a'
down_revision = 'a15d880176aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record', 'success',
               existing_type=mysql.INTEGER(),
               comment='用例执行是否成功 1 成功  2 失败',
               existing_nullable=False)
    op.add_column('test_case', sa.Column('exp_result', sa.JSON(), nullable=False, comment='预期结果  {"jmespath表达式: 值"}'))
    op.add_column('test_case', sa.Column('need_save', sa.JSON(), nullable=False, comment='本次执行后需要保存的值  ["jmespath表达式"]  保存在redis中{用例id_表达式:值}'))
    op.add_column('test_case', sa.Column('caseOrder', sa.Integer(), nullable=False, comment='用例执行顺序'))
    op.add_column('test_case', sa.Column('func_module_id', sa.Integer(), nullable=True, comment='三级模块的id'))
    op.add_column('test_case', sa.Column('status', sa.Integer(), nullable=True, comment='当前用例状态 0 就绪  1 进行中  2  成功  3  失败'))
    op.alter_column('test_case', 'dataType',
               existing_type=mysql.VARCHAR(length=10),
               comment='入参类型  post  json',
               existing_nullable=False)
    op.create_foreign_key(None, 'test_case', 'func_module', ['func_module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.alter_column('test_case', 'dataType',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='入参类型  post  json',
               existing_nullable=False)
    op.drop_column('test_case', 'status')
    op.drop_column('test_case', 'func_module_id')
    op.drop_column('test_case', 'caseOrder')
    op.drop_column('test_case', 'need_save')
    op.drop_column('test_case', 'exp_result')
    op.alter_column('exe_case_record', 'success',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用例执行是否成功 1 成功  2 失败',
               existing_nullable=False)
    # ### end Alembic commands ###
