"""empty message

Revision ID: 44ddc8093e68
Revises: a989e7b74217
Create Date: 2022-03-27 15:39:51.582228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ddc8093e68'
down_revision = 'a989e7b74217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('caseOrder', table_name='test_case')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('caseOrder', 'test_case', ['caseOrder'], unique=False)
    # ### end Alembic commands ###
