"""empty message

Revision ID: 51cdd24bbe68
Revises: 93133fd5f504
Create Date: 2022-04-14 21:54:53.061154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51cdd24bbe68'
down_revision = '93133fd5f504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'consume',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_comment='请求耗时',
               existing_nullable=True)
    op.alter_column('test_case', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'role_id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('test_case', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('exe_case_record_detail', 'consume',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_comment='请求耗时',
               existing_nullable=True)
    # ### end Alembic commands ###
