"""empty message

Revision ID: 541363c9cc7f
Revises: 06cb13258769
Create Date: 2022-03-31 10:15:55.218690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541363c9cc7f'
down_revision = '06cb13258769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exe_case_record_detail', sa.Column('caseName', sa.String(length=10), nullable=False, comment='用例名称'))
    op.add_column('wait_exe_case', sa.Column('caseOrder', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wait_exe_case', 'caseOrder')
    op.drop_column('exe_case_record_detail', 'caseName')
    # ### end Alembic commands ###
