"""empty message

Revision ID: 73eea307f5e7
Revises: 3cf6e5a62e2a
Create Date: 2022-03-28 15:49:48.726057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73eea307f5e7'
down_revision = '3cf6e5a62e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('reqType', sa.String(length=10), nullable=False, comment='请求类型  get post '))
    op.alter_column('test_case', 'dataType',
               existing_type=mysql.VARCHAR(length=10),
               comment='入参类型  data json ',
               existing_comment='入参类型  post  json',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case', 'dataType',
               existing_type=mysql.VARCHAR(length=10),
               comment='入参类型  post  json',
               existing_comment='入参类型  data json ',
               existing_nullable=False)
    op.drop_column('test_case', 'reqType')
    # ### end Alembic commands ###
