"""empty message

Revision ID: a189baa2fbb4
Revises: b64686e32f3a
Create Date: 2022-04-02 11:56:00.202395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a189baa2fbb4'
down_revision = 'b64686e32f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exe_case_record_detail', sa.Column('status', sa.Integer(), nullable=False, comment='用例执行是否成功 0 未开始 1 成功  2 失败'))
    op.drop_column('exe_case_record_detail', 'success')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exe_case_record_detail', sa.Column('success', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用例执行是否成功 0 未开始 1 成功  2 失败'))
    op.drop_column('exe_case_record_detail', 'status')
    # ### end Alembic commands ###
