"""empty message

Revision ID: ab68bdf7fdb1
Revises: 729d80cc1e78
Create Date: 2022-03-31 08:54:43.619528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab68bdf7fdb1'
down_revision = '729d80cc1e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('res', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'res')
    # ### end Alembic commands ###
