"""empty message

Revision ID: b64686e32f3a
Revises: 18c83d14c83e
Create Date: 2022-03-31 10:18:22.910495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b64686e32f3a'
down_revision = '18c83d14c83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'res',
               existing_type=mysql.JSON(),
               nullable=True,
               existing_comment='返回值')
    op.alter_column('exe_case_record_detail', 'success',
               existing_type=mysql.INTEGER(),
               comment='用例执行是否成功 0 未开始 1 成功  2 失败',
               existing_comment='用例执行是否成功 1 成功  2 失败',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exe_case_record_detail', 'success',
               existing_type=mysql.INTEGER(),
               comment='用例执行是否成功 1 成功  2 失败',
               existing_comment='用例执行是否成功 0 未开始 1 成功  2 失败',
               existing_nullable=False)
    op.alter_column('exe_case_record_detail', 'res',
               existing_type=mysql.JSON(),
               nullable=False,
               existing_comment='返回值')
    # ### end Alembic commands ###
