"""empty message

Revision ID: ca662915758f
Revises: a189baa2fbb4
Create Date: 2022-04-02 14:29:00.628323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca662915758f'
down_revision = 'a189baa2fbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exe_case_record_detail_ibfk_1', 'exe_case_record_detail', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('exe_case_record_detail_ibfk_1', 'exe_case_record_detail', 'test_case', ['caseId'], ['id'])
    # ### end Alembic commands ###
